name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install Obfuscated Garble
        run: go install mvdan.cc/garble@latest

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev build-essential curl file git
          sudo apt install -y gcc-13 gcc-13-aarch64-linux-gnu
          sudo apt install -y g++-13-aarch64-linux-gnu

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build for Linux universal
        if: matrix.os == 'ubuntu-latest'
        run: |
          go mod tidy
          wails build --tags webkit2_41 -clean -obfuscated -o code-search-golang-linux-universal
        working-directory: .

      - name: Build for Linux arm64
        if: matrix.os == 'ubuntu-latest'
        run: |
          go mod tidy
          export CC=gcc-13-aarch64-linux-gnu 
          export CXX=g++-13-aarch64-linux-gnu
          export CGO_ENABLED=0
          wails build -platform linux/arm64 --tags webkit2_41 -clean -obfuscated -o code-search-golang-linux-arm64
        working-directory: .

      - name: Build for Linux amd64
        if: matrix.os == 'ubuntu-latest'
        run: |
          go mod tidy
          wails build -platform linux/amd64 --tags webkit2_41 -clean -obfuscated -o code-search-golang-linux-amd64
        working-directory: .

      - name: Build for Windows universal
        if: matrix.os == 'windows-latest'
        run: |
          go mod tidy
          wails build -clean -obfuscated -o code-search-golang-windows-universal
        shell: pwsh

      - name: Build for Windows arm64
        if: matrix.os == 'windows-latest'
        run: |
          go mod tidy
          set CGO_ENABLED=0
          wails build -platform windows/arm64 -clean -obfuscated -o code-search-golang-windows-arm64
        shell: pwsh

      - name: Build for Windows amd64 (64bit)
        if: matrix.os == 'windows-latest'
        run: |
          go mod tidy
          wails build -platform windows/amd64 -clean -obfuscated -o code-search-golang-windows-amd64
        shell: pwsh

      - name: Upload Artifacts (Linux Universal)
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: code-search-golang-linux-universal
          path: build/bin/code-search-golang-linux-universal

      - name: Upload Artifacts (Linux arm64)
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: code-search-golang-linux-arm64
          path: build/bin/code-search-golang-linux-arm64

      - name: Upload Artifacts (Linux amd64)
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: code-search-golang-linux-amd64
          path: build/bin/code-search-golang-linux-amd64

      - name: Upload Artifacts (Windows Universal)
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: code-search-golang-windows-universal
          path: build/bin/code-search-golang-windows-universal.exe

      - name: Upload Artifacts (Windows amd64)
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: code-search-windows-amd64
          path: build/bin/code-search-golang-windows-amd64.exe

      - name: Upload Artifacts (Windows arm64)
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: code-search-windows-arm64
          path: build/bin/code-search-golang-windows-arm64.exe
