name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install Obfuscated Garble
        run: go install mvdan.cc/garble@latest

      - name: Install Linux Dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev
          sudo apt install -y libwebkit2gtk-4.1-dev build-essential curl file git

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build for Linux
        run: |
          go mod tidy
          wails build -platform linux --tags webkit2_41 -clean -obfuscated -o code-search-golang-linux
        working-directory: .

      - name: Build for Windows
        run: |
          go mod tidy
          wails build -platform windows -clean -obfuscated -o code-search-golang-windows
        shell: pwsh

      - name: Upload Artifacts (Linux Universal)
        uses: actions/upload-artifact@v4
        with:
          name: code-search-golang-linux
          path: build/bin/code-search-golang-linux

      - name: Upload Artifacts (Windows Universal)
        uses: actions/upload-artifact@v4
        with:
          name: code-search-golang-windows
          path: build/bin/code-search-golang-windows.exe
