name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install Obfuscated Garble
        run: go install mvdan.cc/garble@latest

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev build-essential curl file git

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          go mod tidy
          wails build --tags webkit2_41 -clean -obfuscated
        working-directory: .

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          go mod tidy
          wails build -clean -obfuscated
        shell: pwsh

      - name: Upload Artifacts (Linux)
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: code-search-linux
          path: build/bin/code-search-golang

      - name: Upload Artifacts (Windows)
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: code-search-windows
          path: build/bin/code-search-golang.exe
